services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: shop_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shop_net

  backend:
    build: ./backend
    restart: always
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: shop_user
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: shop_db
      JWT_SECRET: ${JWT_SECRET}
      LOG_LEVEL: info
      DATABASE_URL: "postgresql://shop_user:${DB_PASSWORD}@postgres:5432/shop_db?schema=public"
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - postgres
    networks:
      - shop_net

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    networks:
      - shop_net

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend
      - grafana
      - prometheus
      - jenkins
    networks:
      - shop_net

  node-exporter:
    image: prom/node-exporter:latest
    restart: always
    networks:
      - shop_net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - shop_net

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - shop_net

  loki:
    image: grafana/loki:latest
    restart: always
    networks:
      - shop_net

  promtail:
    image: grafana/promtail:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./monitoring/promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - shop_net

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    networks:
      - shop_net

  jenkins:
    image: jenkins-docker
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - shop_net

networks:
  shop_net:

volumes:
  pg_data:
  uploads_data:
  jenkins_home: