apiVersion: v1
kind: Service
metadata:
  name: shop-app-frontend
  namespace: shop-app
spec:
  selector:
    app: shop-app-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
