server {
    listen 80;
    server_name shop.mylab.local localhost;

    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
    }

    location /api/ {
        proxy_pass http://backend:3000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name grafana.shop.local;

    location / {
        proxy_pass http://grafana:3000;
        proxy_set_header Host $host;
    }
}

server {
    listen 80;
    server_name prometheus.shop.local;

    location / {
        proxy_pass http://prometheus:9090;
        proxy_set_header Host $host;
    }
}